market/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sarpenstein.urls', namespace="orders")),
]

sarpenstein/urls.py
from django.conf.urls import url
from . import views

app_name = 'sarpenstein'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'register', views.register, name='register'),
	url(r'login', views.login, name='login'),
	url(r'result', views.search, name='search'),
	url(r'search', views.product, name='search-page'),
]

sarpenstein/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.utils import timezone
# Create your models here.
class Device(models.Model):
	Device_type = models.CharField(max_length=50)
	Brand_name = models.CharField(max_length=100)
	RAM = models.CharField(max_length = 15)
	Storage_size = models.CharField(max_length = 15)
	Screen_size = models.CharField(max_length=10)
	Cost = models.IntegerField()
	Supplier = models.CharField(max_length = 50)
	def __str__(self):
		return self.Device_type

class Customer(models.Model):
	Name = models.CharField(max_length=50)
	def __str__(self):
		return self.Name

class Sale(models.Model):
	Customer_id = models.ForeignKey(Customer)
	Purchase_Date = models.DateTimeField(timezone.now())
	device = models.ForeignKey(Device)
	Amount_Paid = models.IntegerField()

	def __str__(self):
		return self.Brand_name

sarpenstein/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email', max_length=100)
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', )

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(LoginForm, self).clean(*args, **kwargs)
    class Meta:
        model = User
        fields = ('username', 'password', )

sarpenstein/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from .forms import *
from .models import *
from .HEOM import *

# Create your views here.
def index(request):
	return render(request, "sarpenstein/index.html", {})

def laptops(request):
	devices = Device.objects.filter(Device_type='Laptop')
	return render(request, 'sarpenstein/laptops.html', {'devices':devices})

def home(request):
	return render(request, 'sarpenstein/home.html', {})

def hp(request):
	return render(request, 'sarpenstein/hp.html', {})

def list_products(request):
	devices  = Device.objects.all()
	return render(request, 'sarpenstein/list_products.html', {"devices":devices})

def brand_category(request, b):
	
	devices  = Device.objects.filter(Brand_name__exact=b)
	return render(request, 'sarpenstein/tecno.html', {"devices":devices})
def search(request):
	return render(request, 'sarpenstein/search.html', {})

def product(request):
	Brand_names = Device.objects.values('Brand_name').distinct()
	Device_types = Device.objects.values('Device_type').distinct()
	data = ''
	# try:
	if request.GET['device_type'] == '':
		Device_type = None
	else:
		Device_type = request.GET['device_type']
		

	if request.GET['brand_name'] == '':
		Brand_name = None
	else:
		Brand_name = request.GET['brand_name']

	if request.GET['ram'] == '':
		RAM = None
	else:
		RAM = int(request.GET['ram'])

	if request.GET['storage_size'] == '':
		Storage_size = None
	else:
		Storage_size = int(request.GET['storage_size'])

	if request.GET['screen_size'] == '':
		Screen_size = None
	else:
		Screen_size = int(request.GET['screen_size'])

	if request.GET['cost'] == '':
		Cost = None
	else:
		Cost = int(request.GET['cost'])

	search_result=Device.objects.filter(Brand_name = Brand_name)#Device_type=Device_type)
	data = Device.objects.all()
	return render(request, 'sarpenstein/results.html', {'search_result': search_result})
	# heom_obj = HEOMClass(497458, 134)
	# heom_score_list = []
	# for device in data:
	# 	scores_list = []
	# 	scores_list.append(heom_obj.h_i(Device_type, Device.Device_type, "categorical"))
	# 	scores_list.append(heom_obj.h_i(Brand_name, Device.Brand_name, "categorical"))
	# 	scores_list.append(heom_obj.h_i(RAM, Device.RAM, "categorical"))
	# 	scores_list.append(heom_obj.h_i(Storage_size, Device.Storage_size, "categorical"))
	# 	scores_list.append(heom_obj.h_i(Screen_size, Device.Screen_size, "categorical"))
	# 	scores_list.append(heom_obj.h_i(Cost, Device.Cost, "regular"))
	# 	heom_score_list.append([Device.id, heom_obj.heom(scores_list)])

	# sorted_heom_score_list = sorted(heom_score_list, key=lambda x: x[1])[0:10]
	# search_result = []
	# for x in sorted_heom_score_list:
	# 	b = Device.objects.get(pk = int(x[0]))
	# 	search_result.append(b)
	# 	print(x, b)
	# return render(request, 'sarpenstein/results.html', {'search_result': search_result})
	# except TypeError:
	# 	if request.user.is_authenticated:
	# 		return render (request, 'sarpenstein/search.html', {'error': 'Wrong Data Type Entered for an Integer Field', 'Brand_names': Brand_names, 'Device_types' : Device_types})
	# 	return render (request, 'sarpenstein/search.html', {'error': ' Wrong Data Type Entered for an Integer Field', 'Brand_names': Brand_names, 'Device_types' : Device_types})
	# # return render(request, 'sarpenstein/search.html', {'data': data, 'request': request})


def register(request):
	form = RegisterForm(request.POST or None)
	if request.user.is_authenticated:
		return HttpResponseRedirect('/home')
	if request.method == 'POST':
		if form.is_valid():
			user = form.save()
			user.refresh_from_db()  # load the profile instance created by the signal
			user.save()
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=user.username, password=raw_password)
			login(request, user)
			return HttpResponseRedirect('/home')
	else:
		form2 = RegisterForm(request.POST or None)
	return render(request, 'sarpenstein/register.html', {'form': form})

def login(request):
	if request.user.is_authenticated:
		return HttpResponseRedirect('/home')
	form = LoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		user = authenticate(username=username, password=password)
		login(request, user)
		return HttpResponseRedirect('/home')
	return render(request, 'sarpenstein/login.html', {'form': form})

def logout(request):
	logout(request)
	return HttpResponseRedirect('/')

def home2(request):
	return render(request, 'sarpenstein/home2.html', {})

sarpenstein/templates/sarpenstein/home.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <title>Sarpenstein : The Global Tech Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
  body {
      font: 400 15px Lato, sans-serif;
      line-height: 1.8;
      color: #818181;
  }
  h2 {
      font-size: 24px;
      text-transform: uppercase;
      color: #303030;
      font-weight: 600;
      margin-bottom: 30px;
  }
  h4 {
      font-size: 19px;
      line-height: 1.375em;
      color: #303030;
      font-weight: 400;
      margin-bottom: 30px;
  }  
  .jumbotron {
      background-color: #696969;
      color: #fff;
      padding: 100px 25px;
      font-family: Josefin Slab, sans-serif;
  }
  .container-fluid {
      padding: 60px 50px;
  }
  .bg-grey {
      background-color: #f6f6f6;
  }
  .logo-small {
      color: #000000;
      font-size: 50px;
  }
  .logo {
      color: #000000;
      font-size: 200px;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail img {
      width: 100%;
      height: 100%;
      margin-bottom: 10px;
  }
  .carousel-control.right, .carousel-control.left {
      background-image: none;
      color: #000000;
  }
  .carousel-indicators li {
      border-color: #000000;
  }
  .carousel-indicators li.active {
      background-color: #000000;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }
  .navbar {
      margin-bottom: 0;
      background-color: #000000;
      z-index: 9999;
      border: 0;
      font-size: 12px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #000000 !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #000000;
  }
  .slideanim {visibility:hidden;}
  .slide {
      animation-name: slide;
      -webkit-animation-name: slide;
      animation-duration: 1s;
      -webkit-animation-duration: 1s;
      visibility: visible;
  }
  @keyframes slide {
    0% {
      opacity: 0;
      transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide {
    0% {
      opacity: 0;
      -webkit-transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      -webkit-transform: translateY(0%);
    }
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
    .btn-lg {
        width: 100%;
        margin-bottom: 35px;
    }
  }
  @media screen and (max-width: 480px) {
    .logo {
        font-size: 150px;
    }
  }
  </style>

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'sarpenstein:home' %}">Sarpenstein</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'sarpenstein:home' %}">HOME</a></li>
        <li><a href = "{% url 'sarpenstein:search' %}">SEARCH</a></li>
        <!-- <li><a href="#services">BEST DEALS!</a></li> -->
        <li><a href="sarpenstein : index">CART</a></li>
        <li><a href="{% url 'sarpenstein:register' %}">REGISTER</a></li>
        <li><a href="{% url 'sarpenstein:login' %}">LOGIN</a></li>
        <!-- <li><a href="#contact">CONTACT</a></li> -->
      </ul>
    </div>
  </div>
</nav>


<!--<div class="jumbotron text-center">
  <form>
   <div class="input-group">
      <input type="text" class="form-control" size="20" placeholder="Search" required>
      <div class="input-group-btn">
        <button type="button" class="btn btn-danger">Find</button>
      </div>
    </div>
  </form>
</div>
-->

  <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
       
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
      <img src="{% static '/images/smart.jpg' %}" alt="smart" width="100%" height="5">
       <!-- <h4>"This company is the best. I am so happy with the result!"<br><span>Michael Roe, Vice President, Comment Box</span></h4>-->
      </div>
      <div class="item">
        <img src="{% static '/images/smart3.jpg' %}" alt="smart3" width="100%" height="5">
      </div>
      <div class="item">
         <img src="{% static '/images/smart2.jpg' %}" alt="smart2" width="100%" height="5">
      </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<!--testing end-->









<!-- Container (Services Section) -->
<div id="services" class="container-fluid text-center">
  <h2>INSANE DEALS!!!</h2>
  <h4>Nothing here less than 20% off!!!</h4>
  <br>
  <div class="row slideanim">
    <div class="col-sm-4">
       <a href=""><img src="{% static 'images/tecno.jpg' %}" height="150"></a>
    </div>
    <div class="col-sm-4">
      <span class="social social-apple"></span>
       <a href=""><img src="{% static 'images/1.jpg' %}" height="150"></a>
    </div>
    <div class="col-sm-4">
      <a href=""><img src="{% static 'images/tecno2.jpg' %}" height="140"></a>
      <p><strong>TECNO</strong></p>
    </div>
  </div>
  <br><br>
  <div class="row slideanim">
    <div class="col-sm-4">
      <a href=""><img src="{% static 'images/lenovo.jpg' %}" width:200; height="150"></a>
      <p><strong>Lenovo</strong></p>
    </div>
    <div class="col-sm-4">
      <a href=""><img src="{% static 'images/hp2.jpg' %}" height="150"></a>
      <p><strong>Hewlett-Packard</strong></p>
    </div>
    <div class="col-sm-4">
      <a href=""><img src="{% static 'images/dell.jpg' %}" height="150"></a>
      <p><strong>DELL</strong></p>
    </div>
  </div>
</div>

<!-- Container (Portfolio Section) -->
<div id="portfolio" class="container-fluid text-center bg-grey">
  <h2>SUGGESTED</h2><br>
  <h4>PRODUCTS YOU MIGHT LIKE</h4>
  <div class="row text-center slideanim">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="{% static 'images/acer.jpg' %}" alt="Paris" width="400" height="300">
        <p><strong>ACER</strong></p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="{% static 'images/hp2.jpg' %}" alt="New York" width="400" height="300">
        <p><strong>Hewlett-Packard</strong></p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="{% static 'images/samsung.jpg' %}" alt="San Francisco" width="400" height="300">
        <p><strong>SAMSUNG</strong></p>
      </div>
    </div>
  </div><br>
  
  <h2>What our customers say</h2>
  <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
          <h4>"This company is the best. I am so happy with the products and customer service relationship!"<br><span>Michael Roe, Vice President, Comment Box</span></h4>
        </div>
              <div class="item">
                   <h4>"One word... WOW!!"<br><span>John Doe, Salesman, Rep Inc</span></h4>
              </div>
                      <div class="item">
                            <h4>"Could I... BE any more happy with this company..SARPENSTINE?"<br><span>Chandler Bing (Actor)</span></h4>
                      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<!-- Container (Contact Section) -->
<div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5">
      <p>Contact us and we'll get back to you within 24 hours.</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Covenant University, Ota</p>
      <p><span class="glyphicon glyphicon-phone"></span> +234805432134</p>
      <p><span class="glyphicon glyphicon-envelope"></span> covenantuniversity@edu.ng</p>
    </div>
    <div class="col-sm-7 slideanim">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>
</div>
`
<footer class="container-fluid text-center">
  <a href="#myPage" title="To Top">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <p>Website powered by Python Developers  <a href="https://covenantuniversity.edu.ng" title="Visit Covenant">covenantuniversity.edu.ng</a></p>
</footer>

<script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 900, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
        window.location.hash = hash;
      });
    } // End if
  });
  
  $(window).scroll(function() {
    $(".slideanim").each(function(){
      var pos = $(this).offset().top;

      var winTop = $(window).scrollTop();
        if (pos < winTop + 600) {
          $(this).addClass("slide");
        }
    });
  });
})
</script>

</body>
</html>

sarpenstein/templates/sarpenstein/results.html
{% load static %}
 <title>Sarpenstein : The Global Tech Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
  body {
      font: 400 15px Lato, sans-serif;
      line-height: 1.8;
      color: #818181;
  }
  h2 {
      font-size: 24px;
      text-transform: uppercase;
      color: #303030;
      font-weight: 600;
      margin-bottom: 30px;
  }
  h4 {
      font-size: 19px;
      line-height: 1.375em;
      color: #303030;
      font-weight: 400;
      margin-bottom: 30px;
  }  
  .jumbotron {
      background-color: #696969;
      color: #fff;
      padding: 100px 25px;
      font-family: Josefin Slab, sans-serif;
  }
  .container-fluid {
      padding: 60px 50px;
  }
  .bg-grey {
      background-color: #f6f6f6;
  }
  .logo-small {
      color: #000000;
      font-size: 50px;
  }
  .logo {
      color: #000000;
      font-size: 200px;
  }
  .thumbnail {
      padding: 0 0 15px 0;
      border: none;
      border-radius: 0;
  }
  .thumbnail img {
      width: 100%;
      height: 100%;
      margin-bottom: 10px;
  }
  .carousel-control.right, .carousel-control.left {
      background-image: none;
      color: #000000;
  }
  .carousel-indicators li {
      border-color: #000000;
  }
  .carousel-indicators li.active {
      background-color: #000000;
  }
  .item h4 {
      font-size: 19px;
      line-height: 1.375em;
      font-weight: 400;
      font-style: italic;
      margin: 70px 0;
  }
  .item span {
      font-style: normal;
  }
  .navbar {
      margin-bottom: 0;
      background-color: #000000;
      z-index: 9999;
      border: 0;
      font-size: 12px !important;
      line-height: 1.42857143 !important;
      letter-spacing: 4px;
      border-radius: 0;
      font-family: Montserrat, sans-serif;
  }
  .navbar li a, .navbar .navbar-brand {
      color: #fff !important;
  }
  .navbar-nav li a:hover, .navbar-nav li.active a {
      color: #000000 !important;
      background-color: #fff !important;
  }
  .navbar-default .navbar-toggle {
      border-color: transparent;
      color: #fff !important;
  }
  footer .glyphicon {
      font-size: 20px;
      margin-bottom: 20px;
      color: #000000;
  }
  .slideanim {visibility:hidden;}
  .slide {
      animation-name: slide;
      -webkit-animation-name: slide;
      animation-duration: 1s;
      -webkit-animation-duration: 1s;
      visibility: visible;
  }
  @keyframes slide {
    0% {
      opacity: 0;
      transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      transform: translateY(0%);
    }
  }
  @-webkit-keyframes slide {
    0% {
      opacity: 0;
      -webkit-transform: translateY(70%);
    } 
    100% {
      opacity: 1;
      -webkit-transform: translateY(0%);
    }
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
    .btn-lg {
        width: 100%;
        margin-bottom: 35px;
    }
  }
  @media screen and (max-width: 480px) {
    .logo {
        font-size: 150px;
    }
  }
  </style>

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'sarpenstein:home' %}">Sarpenstein</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'sarpenstein:home' %}">HOME</a></li>
        <li><a href = "{% url 'sarpenstein:search' %}">SEARCH</a></li>
        <!-- <li><a href="#services">BEST DEALS!</a></li> -->
        <li><a href="sarpenstein : index">CART</a></li>
        <li><a href="{% url 'sarpenstein:register' %}">REGISTER</a></li>
        <li><a href="{% url 'sarpenstein:login' %}">LOGIN</a></li>
        <!-- <li><a href="#contact">CONTACT</a></li> -->
      </ul>
    </div>
  </div>
</nav>

<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
  {% for item in search_result %}
  <div class="panel panel-default">
      <div class="panel-heading">{{ item.Brand_name}}</div>
      <div class="panel-body">
      <p>{{ item.Device_type}}</p>
      <p>   {{ item.RAM}} GB </p>
      <p>{{ item.Storage_size}} GB</p>
      <p>{{ item.Screen_size }} inches</p>
      <p> {{ item.Cost }}</p>
    </div>
  </div>

  

  {% endfor %}
  </div>
    <div class="col-md-2"></div>
</div>